project:
  type: website
  resources:
    - CNAME
    - kiwi

format:
  html:
    theme: full
    css: styles.css
    default-image-extension: ""
    grid:
      body-width: 1000px

website:
  title: "Shiying Xiao"
  description: "Personal Website of Shiying Xiao"
  site-url: https://carol-seven.github.io/
  navbar:
    background: "#F2F2F2"
    left:
      - text: Home
        file: index.qmd
      - text: Research
        file: research.qmd
      - text: Publications
        file: publications.qmd
      - text: Software
        file: software.qmd
      - text: CV
        file: CV/CV_ShiyingXiao.pdf
      - text: "![](kiwi/paws.svg)"
        file: kiwi.qmd
    right:
      - icon: envelope
        href: mailto:shiying.xiao@outlook.com
      - icon: github
        href: https://github.com/Carol-seven
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=s-TZZPgAAAAJ
      - text: "{{< ai orcid size=xl >}}"
        href: https://orcid.org/0000-0002-8846-3258
      - text: "{{< ai researchgate size=xl >}}"
        href: https://www.researchgate.net/profile/Shiying-Xiao-2
    search: true

  page-footer:
    left: "&copy; Copyright 2025, Shiying Xiao."
    right: "Prepared with [Quarto](https://quarto.org)."

execute:
  freeze: auto
